In [1]:
import json


In [4]:
from sklearn.linear_model import LinearRegression

In [3]:
with open('./A_0.json') as fp:
    data = json.load(fp)

lines = data.keys()
values = data.values()
X = []
for line in lines:
    tmp = line.split('.')[0]
    X.append(int(tmp))
print(X)
Y = []
for ex in values:
    Y.append(sum(ex) / 2)

print(Y)
print(len(X),len(Y))
    
    


[1, 1024, 128, 16, 2, 2048, 256, 32, 4, 4096, 512, 64, 8, 8192, 16384, 262144, 32768, 131072]
[0.0, 0.6875, 0.0078125, 0.0, 0.0, 3.15625, 0.0234375, 0.0, 0.0, 13.140625, 0.140625, 0.0, 0.0, 56.2421875, 146.15625, 41263.953125, 610.53125, 9797.4140625]
18 18


In [9]:
import numpy as np
X = np.array(X).reshape(-1,1)
reg = LinearRegression().fit(X.reshape(-1,1), Y)

[[     1]
 [  1024]
 [   128]
 [    16]
 [     2]
 [  2048]
 [   256]
 [    32]
 [     4]
 [  4096]
 [   512]
 [    64]
 [     8]
 [  8192]
 [ 16384]
 [262144]
 [ 32768]
 [131072]]


In [11]:
reg.predict(np.array([524288, 1048576, 2097152, 4194304]).reshape(-1,1))

array([ 74114.36588267, 148985.43098969, 298727.56120374, 598211.82163184])

In [16]:
data = {}
with open('./B_0.json') as fp:
    data = json.load(fp)

lines = data.keys()
values = data.values()
X_B = []
for line in lines:
    tmp = line.split('.')[0]
    X_B.append(int(tmp))
print(X_B)
Y_B = []
for ex in values:
    Y_B.append(sum(ex) / 2)

print(Y_B)
print(len(X_B),len(Y_B))

[1, 1024, 128, 16, 2, 2048, 256, 32, 4, 4096, 512, 64, 8, 8192, 131072, 16384, 262144]
[0.0, 1.5078125, 0.0, 0.0, 0.0, 7.203125, 0.046875, 0.0, 0.0, 28.546875, 0.2421875, 0.0, 0.0, 107.9609375, 18059.375, 264.859375, 71607.8125]
17 17


In [17]:
X_B = np.array(X_B).reshape(-1,1)
reg_2 = LinearRegression().fit(X_B.reshape(-1,1), Y_B)
reg_2.predict(np.array([65536, 524288, 1048576, 2097152, 4194304]).reshape(-1,1))

array([  15413.44850916,  130047.32856658,  261057.47720363,
        523077.77447774, 1047118.36902596])